### ISSUE TITLE
Select dataset

### ISSUE THREAD

**Issue by alexandervansteel** [wangem123/cis467#1]
Determine which database we are going to use.

**Comment by JoelVK** [comment]
can this be considered closed as we have our dataset?

**Comment by alexandervansteel** [comment]
umm... i had closed it because i started working on the label. but then i actually found a better data set with 28709 examples instead of just 500 some. so i'm taking a quick peek into that

**Comment by alexandervansteel** [comment]
so after exploration, i was able to find a much larger dataset. this one has images that are taken at 5 different angles; left, right, partial left, partial right, and front facing.
all the images are also in colour, which this is a good thing. both data sets are small. but with the images being colour, it allows us to artificially increase the size of the database through colour manipulation to get much better results. 
additionally, the file name for the image has the emotion in it, rather than in another directory inside a file. so that simplifies getting the emotion. 
i placed it in the drive

**Comment by JoelVK** [comment]
Looking at the new data set, I have a few questions. 

Since the only use case for the project is for a webcam, in which the user is almost always looking directly at the camera, will the left and right images be at all useful? 

Also, since we want to pick up on nuanced emotion, might it be better to have the first data set to get transitional emotions?


A quick back of the napkin calc gives me about 2940 images from the second data set, based on only being able to use the front and partial turned pictures (140 people/folders * 21 usable images per folder) . That doesn't include any image manipulations. For the first dataset, I get about 4060 images, based on about 11 images in each file * about 5 emotions per person * 123 people * only being able to use 60% of the images on account of them being neutral. 

I don't know if them being the same people would reduce their usefulness as training data, but its something to consider.

**Comment by alexandervansteel** [comment]
The CK+ dataset only has 257, or something on the order of that, images that are labeled out of the 573 total images in the dataset. I forget the exact numbers right now, but due to the rubric they created in the study putting together the dataset, images that did not meet certain criteria did not get a label.
So the CK dataset has even less usable images.

**Comment by JoelVK** [comment]
I guess i'm still a bit confused at how the second data set is better than the first. looking into both further, I can see that each folder in the KDEF data set holds 7 front facing images of each emotion, and another 14 of each emotion not facing the camera directly. the rest of the images in each folder are profile shots, which i can't imagine will be useful. Additionally, there are folder sets AF, AM, BF, and BM for which A and B are the same actors, with the same emotions and angles, just a retaken photo. That gives me (7 front facing + 14 angled shots)* 70 people * 2 shots = 2940 pictures.

For the original data set, while they are all black and white and front facing, each of the 327 labeled sequences each having a minimum of 11 pictures. So 327 labeled sets * ~66% having detectable emotion * ~11 images gives me 2374 usable images. As well, the first data set has 123 subjects whereas the second set only has 70.

While I can see that the first set has less images to use in total, my issue is that our primary use is having the user face the camera more or less directly, and that having less images of people facing the camera for it to train on will make it less accurate than to have it train on all front facing images.

**Comment by alexandervansteel** [comment]
Running` find DIR_NAME -type f | wc -l` in the directory with the labels shows that there are only 327 text files with a label descriptor for the entire directory.
When running the command to count the number of images in the KDEF, since every single image is guaranteed to be labeled, the count comes back with: 5040. Assuming we cut out the full left and full right, since there is a use case scenario for a user to have their face partially turned away into a half left or half right (one could even argue full left or full right in extreme situations as someone turns away to make a face which is common in certain cultures, especially Asian ones), we would have access to 3/5 of the 5040 images. This reduces that number down to 3024 labeled images. Which is significantly more than the the CK+.
There are a total of 10727 images in CK+ dataset, but only 327 of them actually met the criteria for being labeled. So if we did want to use that dataset, we would have to go through and manually create labels for the images. There is not a way to go through and manually fill in all the missing labels. The only images labeled are the final images of the CK+ dataset. So of the 593 directories with images in them, only 327 of them actually have a label. Of those 327 sets, only the final image in the set has a label. So even then, we would need to determine a cut off point where neutral face goes away and the image label starts to kick in.
Another issue I found with the CK+ dataset while looking at a website talking about it was that their is a disparity in the number of emotional expressions. I can't remember the exact number, but certain emotions like anger or disgust only have something like 10 labels.

**Comment by JoelVK** [comment]
I can see your point about the difficulty with extending the labels, and I didn't know the disparity with the emotions for the first data set.

Thanks for explaining that to me. So assuming my lack of understanding is the only thing holding this up,  this can be moved to closed?

**Comment by alexandervansteel** [comment]
If everyone is good with that, yes we can move it to close.

And don't feel bad about holding it up. That's part of the process, to put checks and balances on each other. I'd rather questions and challenges be brought up than mindlessly closing something.
